- hosts: kvmhost
  roles:
    - setup_kvm_server
    - create_kvm_network
    - create_helper_kvm
    - create_ocp4_kvms
    
- hosts: kvmguest
  roles:
    - update_helper_kvm
    - setup_openshift4

- hosts: kvmhost
  roles:
    - start_ocp4_kvms
