- name: run the bash script to create bootstrap kvms
  command: " /bin/sh {{ role_path }}/files/create_kvm.sh {{ item.name }} {{ kvm_network_name }} {{ disk }} {{ libvirt_image_directory }}"
  with_items:
    - "{{ hostvars['localhost']['bootstrap'] }}"

- name: run the bash script to create master kvms
  command: " /bin/sh {{ role_path }}/files/create_kvm.sh {{ item.name }} {{ kvm_network_name }} {{ disk }} {{ libvirt_image_directory }}"
  with_items:
    - "{{ hostvars['localhost']['masters'] }}"

- name: run the bash script to create worker kvms
  command: " /bin/sh {{ role_path }}/files/create_kvm.sh {{ item.name }} {{ kvm_network_name }} {{ disk }} {{ libvirt_image_directory }}"
  with_items:
    - "{{ hostvars['localhost']['workers'] }}"
